### ISSUE TITLE
Code not compatible with latest version of sktime (SingleSeriesTransformAdaptor)

### ISSUE THREAD

**Issue by ngupta23** [mloning/sktime-m4#1]
Hi @mloning ,

I am having issues running this code since the API seems to have changed since this was done. Particularly, [this line](https://github.com/mloning/sktime-m4/blob/2b51b9c41968c2065b26e655df70a41c0a414e3a/scripts/construct.py#L26). Is there a replacement for `SingleSeriesTransformAdaptor`? is it [`TabularToSeriesAdaptor`](https://github.com/alan-turing-institute/sktime/blob/c57d8829005c4bcd28a2c2bd1816e5ceb6734617/sktime/transformations/series/adapt.py#L34)?

Also, why is this needed? Can I not use the scikit transformer directly without using this adaptor?

Thanks,
Nikhil

**Comment by mloning** [comment]
Hi @ngupta23, yes that's right, it's pinned to `v0.4.0` [here](https://github.com/mloning/sktime-m4/blob/master/requirements.txt). 

Yes, we renamed it for more consistent naming. I believe we need this because scikit-learn doesn't accept and return `pd.Series` for the `X` argument.

**Comment by ngupta23** [comment]
Thank you. I am trying to use the flow in the repo with the latest version of the library. So is [`TabularToSeriesAdaptor`](https://github.com/alan-turing-institute/sktime/blob/c57d8829005c4bcd28a2c2bd1816e5ceb6734617/sktime/transformations/series/adapt.py#L34) the correct replacement for `SingleSeriesTransformAdaptor`?

**Comment by mloning** [comment]
> Thank you. I am trying to use the flow in the repo with the latest version of the library. So is [`TabularToSeriesAdaptor`](https://github.com/alan-turing-institute/sktime/blob/c57d8829005c4bcd28a2c2bd1816e5ceb6734617/sktime/transformations/series/adapt.py#L34) the correct replacement for `SingleSeriesTransformAdaptor`?

Yes, as said, we renamed it for more consistent naming. 🙂

**Comment by ngupta23** [comment]
Thank you for confirming.
